data=
{
   "locations":{
      "ground":[
         {
            "name":"Ajan Kloss",
            "subheader":"The Klosslands",
            "imgUrl":"https://vignette.wikia.nocookie.net/battlefront/images/0/0a/Trospromo1.jpg/revision/latest",
            "summary":{
               "maps":1,
               "online-modes":[
                  "mode/capital-supremacy",
                  "mode/co-op"
               ],
               "offline-modes":[

               ]
            }
         },
         {
            "name":"Bespin",
            "subheader":"Administrator's Palace",
            "imgUrl":"https://cdnb.artstation.com/p/assets/covers/images/004/237/685/large/daniel-cambrand-danielcambrand-03.jpg",
            "summary":{
               "maps":1,
               "online-modes":[
                  "mode/blast",
                  "mode/hvv"
               ],
               "offline-modes":[
                  "mode/campaign",
                  "mode/team-battle",
                  "mode/onslaught",
                  "mode/duel"
               ]
            }
         },
         {
            "name":"Crait",
            "subheader":"Abandoned Rebel Outpost",
            "imgUrl":"https://cdna.artstation.com/p/assets/images/images/009/728/722/large/mikael-andersson-swbfii-mikaelandersson-28.jpg?1520549861",
            "summary":{
               "maps":1,
               "online-modes":[
                  "mode/blast",
                  "mode/galactic-assault"
               ],
               "offline-modes":[
                  "mode/onslaught",
                  "mode/team-battle",
                  "mode/duel"
               ]
            }
         },
         {
            "name":"Death Star II",
            "subheader":"Command Sector North",
            "imgUrl":"img/location/death-star-ii.jpg",
            "summary":{
               "maps":1,
               "online-modes":[
                  "mode/blast",
                  "mode/galactic-assault",
                  "mode/hero-showdown",
                  "mode/hvv",
                  "mode/strike"
               ],
               "offline-modes":[
                  "mode/onslaught",
                  "mode/team-battle",
                  "mode/duel"
               ]
            }
         },
         {
            "name":"Endor",
            "subheader":"Ewok Village",
            "imgUrl":"https://media.contentapi.ea.com/content/legacy/starwars-ea-com/es_MX/starwars/battlefront/news-articles/the-star-wars-battlefront-planets--creating-endor/_jcr_content/featuredImage/renditions/rendition1.img.jpg",
            "summary":{
               "maps":2,
               "online-modes":[
                  "mode/blast",
                  "mode/ewok-hunt",
                  "mode/galactic-assault",
                  "mode/hero-showdown",
                  "mode/hvv",
                  "mode/strike"
               ],
               "offline-modes":[
                  "mode/campaign",
                  "mode/onslaught",
                  "mode/team-battle",
                  "mode/duel"
               ]
            }
         },
         {
            "name":"Endor",
            "subheader":"Research Station 9",
            "imgUrl":"https://media.contentapi.ea.com/content/legacy/starwars-ea-com/es_MX/starwars/battlefront/news-articles/the-star-wars-battlefront-planets--creating-endor/_jcr_content/featuredImage/renditions/rendition1.img.jpg",
            "summary":{
               "maps":2,
               "online-modes":[
                  "mode/blast",
                  "mode/ewok-hunt",
                  "mode/galactic-assault",
                  "mode/hero-showdown",
                  "mode/hvv",
                  "mode/strike"
               ],
               "offline-modes":[
                  "mode/campaign",
                  "mode/onslaught",
                  "mode/team-battle",
                  "mode/duel"
               ]
            }
         },
         {
            "name":"Felucia",
            "subheader":"Tagata",
            "imgUrl":"https://cdn.wccftech.com/wp-content/uploads/2019/09/swbfII_clone_commando.jpg",
            "summary":{
               "maps":1,
               "online-modes":[
                  "mode/capital-supremacy",
                  "mode/co-op"
               ],
               "offline-modes":[
                  "mode/instant-action"
               ]
            }
         },
         {
            "name":"Geonosis",
            "subheader":"Pipeline Junction West",
            "imgUrl":"https://cdnb.artstation.com/p/assets/images/images/014/320/967/large/pontus-ryman-swbfii-pontusryman-07.jpg?1543483500",
            "summary":{
               "maps":2,
               "online-modes":[
                  "mode/blast",
                  "mode/capital-supremacy",
                  "mode/co-op",
                  "mode/galactic-assault",
                  "mode/hvv"
               ],
               "offline-modes":[
                  "mode/instant-action",
                  "mode/onslaught",
                  "mode/team-battle",
                  "mode/duel"
               ]
            }
         },
         {
            "name":"Geonosis",
            "subheader":"Trippa Hive",
            "imgUrl":"https://cdnb.artstation.com/p/assets/images/images/014/320/967/large/pontus-ryman-swbfii-pontusryman-07.jpg?1543483500",
            "summary":{
               "maps":2,
               "online-modes":[
                  "mode/blast",
                  "mode/capital-supremacy",
                  "mode/co-op",
                  "mode/galactic-assault",
                  "mode/hvv"
               ],
               "offline-modes":[
                  "mode/instant-action",
                  "mode/onslaught",
                  "mode/team-battle",
                  "mode/duel"
               ]
            }
         },
         {
            "name":"Hoth",
            "subheader":"Outpost Delta",
            "imgUrl":"https://lumiere-a.akamaihd.net/v1/images/Hoth_d074d307.jpeg",
            "summary":{
               "maps":1,
               "online-modes":[
                  "mode/blast",
                  "mode/galactic-assault",
                  "mode/hero-showdown",
                  "mode/hvv",
                  "mode/strike"
               ],
               "offline-modes":[
                  "mode/onslaught",
                  "mode/team-battle",
                  "mode/duel"
               ]
            }
         },
         {
            "name":"Jakku",
            "subheader":"The Graveyard",
            "imgUrl":"https://cdna.artstation.com/p/assets/images/images/009/033/696/large/anton-kavousi-swbfii-antonkavousi-03.jpg?1516747707",
            "summary":{
               "maps":1,
               "online-modes":[
                  "mode/blast",
                  "mode/galactic-assault",
                  "mode/hero-showdown",
                  "mode/hvv",
                  "mode/strike"
               ],
               "offline-modes":[
                  "mode/campaign",
                  "mode/onslaught",
                  "mode/team-battle",
                  "mode/duel"
               ]
            }
         },
         {
            "name":"Kamino",
            "subheader":"Cloning Facility",
            "imgUrl":"https://vignette.wikia.nocookie.net/battlefront/images/d/d1/Kamino_Facility_Andrew_Hamilton.jpg/revision/latest?cb=20180308210107",
            "summary":{
               "maps":1,
               "online-modes":[
                  "mode/blast",
                  "mode/capital-supremacy",
                  "mode/co-op",
                  "mode/galactic-assault",
                  "mode/hero-showdown",
                  "mode/hvv",
                  "mode/strike"
               ],
               "offline-modes":[
                  "mode/battle-scenarios",
                  "mode/instant-action",
                  "mode/onslaught",
                  "mode/team-battle",
                  "mode/duel"
               ]
            }
         },
         {
            "name":"Kashyyyk",
            "subheader":"Kachirho Beach",
            "imgUrl":"https://i.redd.it/vocninji9jt11.jpg",
            "summary":{
               "maps":2,
               "online-modes":[
                  "mode/blast",
                  "mode/capital-supremacy",
                  "mode/co-op",
                  "mode/galactic-assault",
                  "mode/hero-showdown",
                  "mode/hvv",
                  "mode/strike"
               ],
               "offline-modes":[
                  "mode/instant-action",
                  "mode/onslaught",
                  "mode/team-battle",
                  "mode/duel"
               ]
            }
         },
         {
            "name":"Kashyyyk",
            "subheader":"Kachirho Beach (Treetops)",
            "imgUrl":"https://i.redd.it/vocninji9jt11.jpg",
            "summary":{
               "maps":2,
               "online-modes":[
                  "mode/blast",
                  "mode/capital-supremacy",
                  "mode/co-op",
                  "mode/galactic-assault",
                  "mode/hero-showdown",
                  "mode/hvv",
                  "mode/strike"
               ],
               "offline-modes":[
                  "mode/instant-action",
                  "mode/onslaught",
                  "mode/team-battle",
                  "mode/duel"
               ]
            }
         },
         {
            "name":"Kessel",
            "subheader":"Coaxium Mine",
            "imgUrl":"https://cdna.artstation.com/p/assets/images/images/013/864/392/large/michael-anderson-swbfii-michaelanderson-21.jpg?1541431881",
            "summary":{
               "maps":1,
               "online-modes":[
                  "mode/blast",
                  "mode/hero-showdown",
                  "mode/hvv",
                  "mode/strike"
               ],
               "offline-modes":[
                  "mode/onslaught",
                  "mode/team-battle",
                  "mode/duel"
               ]
            }
         },
         {
            "name":"MC85 Star Cruiser",
            "subheader":"Interior",
            "imgUrl":"img/location/mc85-star-cruiser.jpg",
            "summary":{
               "maps":1,
               "online-modes":[
                  "mode/capital-supremacy"
               ],
               "offline-modes":[

               ]
            }
         },
         {
            "name":"Naboo",
            "subheader":"Theed",
            "imgUrl":"https://vignette.wikia.nocookie.net/battlefront/images/7/79/Naboo_Theed_-_Royal_Palace_%281%29_-_Mikael_Andersson_DICE.jpg",
            "summary":{
               "maps":2,
               "online-modes":[
                  "mode/blast",
                  "mode/capital-supremacy",
                  "mode/co-op",
                  "mode/galactic-assault",
                  "mode/hero-showdown",
                  "mode/hvv",
                  "mode/strike"
               ],
               "offline-modes":[
                  "mode/battle-scenarios",
                  "mode/campaign",
                  "mode/instant-action",
                  "mode/onslaught",
                  "mode/team-battle",
                  "mode/duel"
               ]
            }
         },
         {
            "name":"Naboo",
            "subheader":"Theed Hangar",
            "imgUrl":"https://vignette.wikia.nocookie.net/battlefront/images/7/79/Naboo_Theed_-_Royal_Palace_%281%29_-_Mikael_Andersson_DICE.jpg",
            "summary":{
               "maps":2,
               "online-modes":[
                  "mode/blast",
                  "mode/capital-supremacy",
                  "mode/co-op",
                  "mode/galactic-assault",
                  "mode/hero-showdown",
                  "mode/hvv",
                  "mode/strike"
               ],
               "offline-modes":[
                  "mode/battle-scenarios",
                  "mode/campaign",
                  "mode/instant-action",
                  "mode/onslaught",
                  "mode/team-battle",
                  "mode/duel"
               ]
            }
         },
         {
            "name":"Resurgent Star Destroyer",
            "subheader":"Interior",
            "imgUrl":"img/location/resurgent-class-star-destroyer.jpg",
            "summary":{
               "maps":1,
               "online-modes":[
                  "mode/capital-supremacy"
               ],
               "offline-modes":[

               ]
            }
         },
         {
            "name":"Scarif",
            "subheader":"???",
            "imgUrl":"img/location/scarif.png",
            "summary":{
               "maps":2,
               "online-modes":[
                  "mode/capital-supremacy",
                  "mode/co-op"
               ],
               "offline-modes":[
                  "mode/campaign",
                  "mode/instant-action"
               ]
            },
            "availability":"future-content",
            "alert":"coming-soon"
         },
         {
            "name":"Separatist Dreadnought",
            "subheader":"Interior",
            "imgUrl":"https://cdna.artstation.com/p/assets/images/images/020/328/558/large/saralie-wagstrom-swbf-saraliewagstrom-06.jpg?1567361315",
            "summary":{
               "maps":1,
               "online-modes":[
                  "mode/capital-supremacy",
                  "mode/hvv"
               ],
               "offline-modes":[

               ]
            }
         },
         {
            "name":"Starkiller Base",
            "subheader":"Command Center",
            "imgUrl":"https://cdna.artstation.com/p/assets/images/images/010/231/578/large/marcus-fritze-swbfii-marcusfritze-18.jpg?1523305576",
            "summary":{
               "maps":1,
               "online-modes":[
                  "mode/blast",
                  "mode/galactic-assault",
                  "mode/hero-showdown",
                  "mode/hvv",
                  "mode/strike"
               ],
               "offline-modes":[
                  "mode/battle-scenarios",
                  "mode/campaign",
                  "mode/onslaught",
                  "mode/team-battle",
                  "mode/duel",
                  "mode/tutorial"
               ]
            }
         },
         {
            "name":"Takodana",
            "subheader":"Maz'z Castle",
            "imgUrl":"https://cdnb.artstation.com/p/assets/images/images/009/707/633/large/daniel-rocque-swbfii-danielrocquebengtsson-02.jpg?1520445639",
            "summary":{
               "maps":1,
               "online-modes":[
                  "mode/blast",
                  "mode/galactic-assault",
                  "mode/hero-showdown",
                  "mode/hvv",
                  "mode/strike"
               ],
               "offline-modes":[
                  "mode/battle-scenarios",
                  "mode/campaign",
                  "mode/onslaught",
                  "mode/team-battle",
                  "mode/duel"
               ]
            }
         },
         {
            "name":"Tatooine",
            "subheader":"Jabba's Palace",
            "imgUrl":"https://vignette.wikia.nocookie.net/battlefront/images/d/d9/Mos_Eisley_View.jpg/revision/latest?cb=20180307193130",
            "summary":{
               "maps":2,
               "online-modes":[
                  "mode/blast",
                  "mode/galactic-assault",
                  "mode/hero-showdown",
                  "mode/hvv",
                  "mode/strike"
               ],
               "offline-modes":[
                  "mode/battle-scenarios",
                  "mode/onslaught",
                  "mode/team-battle",
                  "mode/duel"
               ]
            }
         },
         {
            "name":"Tatooine",
            "subheader":"Mos Eisley",
            "imgUrl":"https://vignette.wikia.nocookie.net/battlefront/images/d/d9/Mos_Eisley_View.jpg/revision/latest?cb=20180307193130",
            "summary":{
               "maps":2,
               "online-modes":[
                  "mode/blast",
                  "mode/galactic-assault",
                  "mode/hero-showdown",
                  "mode/hvv",
                  "mode/strike"
               ],
               "offline-modes":[
                  "mode/battle-scenarios",
                  "mode/onslaught",
                  "mode/team-battle",
                  "mode/duel"
               ]
            }
         },
         {
            "name":"Venator",
            "subheader":"Interior",
            "imgUrl":"https://images3.alphacoders.com/883/883581.png",
            "summary":{
               "maps":1,
               "online-modes":[
                  "mode/capital-supremacy",
                  "mode/hvv"
               ],
               "offline-modes":[

               ]
            }
         },
         {
            "name":"Yavin 4",
            "subheader":"The Great Temple",
            "imgUrl":"https://i.redd.it/ig9ectnjbgsz.jpg",
            "summary":{
               "maps":1,
               "online-modes":[
                  "mode/blast",
                  "mode/galactic-assault",
                  "mode/hero-showdown",
                  "mode/hvv",
                  "mode/strike"
               ],
               "offline-modes":[
                  "mode/battle-scenarios",
                  "mode/onslaught",
                  "mode/team-battle",
                  "mode/duel"
               ]
            }
         }
      ],
      "space":[
         {
            "name":"D'Qar",
            "subheader":"Resistance Base Evacuation"
         },
         {
            "name":"Endor",
            "subheader":"Death Star Debris"
         },
         {
            "name":"Fondor",
            "subheader":"Imperial Shipyard"
         },
         {
            "name":"Kamino",
            "subheader":"Research Outpost"
         },
         {
            "name":"Ryloth",
            "subheader":"Lucrehulk Battleship"
         },
         {
            "name":"Unknown Regions",
            "subheader":"Resurgent Star Destroyer"
         }
      ],
      "campaign":[
         {
            "name":"Sullust",
            "imgUrl":"https://vignette.wikia.nocookie.net/battlefront/images/5/56/SWB2-Cache_Grab.jpg",
            "availability":"unavailable",
            "alert":"campaign-only"
         },
         {
            "name":"Vardos",
            "imgUrl":"https://vignette.wikia.nocookie.net/battlefront/images/c/c7/SWB2-Art-Vardos.jpg/revision/latest?cb=20171202011459",
            "availability":"unavailable",
            "alert":"campaign-only"
         },
         {
            "name":"Pillio",
            "imgUrl":"https://vignette.wikia.nocookie.net/battlefront/images/e/e1/SWB2-The_Observatory.jpg/revision/latest?cb=20171202012804",
            "availability":"unavailable",
            "alert":"campaign-only"
         }
      ]
   },
   "characters":{
      "hero":[
         {
            "name":"Anakin Skywalker",
            "subheader":"Jedi Knight",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/anakin/hero/anakin-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/republic"
               ]
            }
         },
         {
            "name":"BB-8",
            "subheader":"Astromech",
            "imgUrl":"img/hero/bb-8.jpg",
            "summary":{
               "factions":[
                  "faction/resistance"
               ]
            }
         },
         {
            "name":"BB-9E",
            "subheader":"Astromech",
            "imgUrl":"img/hero/bb-9e.jpg",
            "summary":{
               "factions":[
                  "faction/first-order"
               ]
            }
         },
         {
            "name":"Boba Fett",
            "subheader":"Bounty Hunter",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/boba-fett/hero-images/boba-fett-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/empire"
               ]
            }
         },
         {
            "name":"Bossk",
            "subheader":"Bounty Hunter",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/bossk/hero/bossk-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/separatists",
                  "faction/empire"
               ]
            }
         },
         {
            "name":"Captain Phasma",
            "subheader":"Stormtrooper",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/phasma/hero/phasma-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/first-order"
               ]
            }
         },
         {
            "name":"Chewbacca",
            "subheader":"Rebel Hero",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/chewbacca/hero/chewie-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/rebels",
                  "faction/republic"
               ]
            }
         },
         {
            "name":"Count Dooku",
            "subheader":"Sith Lord",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/count-dooku/hero/dooku-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/separatists"
               ]
            }
         },
         {
            "name":"Darth Maul",
            "subheader":"Sith Lord",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/darth-maul/hero-images/darth-maul-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/separatists"
               ]
            }
         },
         {
            "name":"Darth Vader",
            "subheader":"Sith Lord",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/darth-vader/hero-images/darth-vader-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/empire"
               ]
            }
         },
         {
            "name":"Emperor Palpatine",
            "subheader":"Sith Lord",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/emperor/hero/emporer-palpatine-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/empire"
               ]
            }
         },
         {
            "name":"Finn",
            "subheader":"Resistance Hero",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/finn/hero/finn-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/resistance"
               ]
            }
         },
         {
            "name":"General Greivous",
            "subheader":"Jedi Hunter",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/grievous/hero/grievous-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/separatists"
               ]
            }
         },
         {
            "name":"Han Solo",
            "subheader":"Scoundrel",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/han-solo/hero-images/han-solo-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/rebels"
               ]
            }
         },
         {
            "name":"Iden Versio",
            "subheader":"Special Forces",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/iden/hero/iden-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/empire"
               ]
            }
         },
         {
            "name":"Kylo Ren",
            "subheader":"Supreme Leader",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/kylo-ren/hero/kylo-ren-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/first-order"
               ]
            }
         },
         {
            "name":"Lando Calrissian",
            "subheader":"Entrepreneur",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/lando/hero/lando-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/rebels"
               ]
            }
         },
         {
            "name":"Leia Organa",
            "subheader":"Princess",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/leia/hero/leia-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/rebels"
               ]
            }
         },
         {
            "name":"Luke Skywalker",
            "subheader":"Jedi Knight",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/luke/hero/luke-skywalker-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/rebels"
               ]
            }
         },
         {
            "name":"Obi-Wan Kenobi",
            "subheader":"Jedi Master",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/obi-wan/hero/obi-wan-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/republic"
               ]
            }
         },
         {
            "name":"Rey",
            "subheader":"Jedi Knight",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/rey/hero-images/rey-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/resistance"
               ]
            }
         },
         {
            "name":"Yoda",
            "subheader":"Jedi Master",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/yoda/hero-images/yoda-hero-lg.jpg",
            "summary":{
               "factions":[
                  "faction/republic"
               ]
            }
         }
      ],
      "reinforcement":[
         {
            "name":"ARC Trooper",
            "subheader":"Infiltrator",
            "imgUrl":"img/reinforcement/infiltrator/arc-trooper.jpg"
         },
         {
            "name":"Commando Droid",
            "subheader":"Infiltrator",
            "imgUrl":"img/reinforcement/infiltrator/commando-droid.jpg"
         },
         {
            "name":"Caphex Spy",
            "subheader":"Infiltrator",
            "imgUrl":"img/reinforcement/infiltrator/caphex-spy.png"
         },
         {
            "name":"Sith Trooper",
            "subheader":"Infiltrator",
            "imgUrl":"img/reinforcement/infiltrator/sith-trooper.jpg"
         },
         {
            "name":"Clone Commando",
            "subheader":"Enforcer",
            "imgUrl":"img/reinforcement/enforcer/clone-commando.jpg"
         },
         {
            "name":"Droideka",
            "subheader":"Enforcer",
            "imgUrl":"img/reinforcement/enforcer/droideka.jpg"
         },
         {
            "name":"B2 Battle Droid",
            "subheader":"Enforcer",
            "imgUrl":"img/reinforcement/enforcer/b2-battle-droid.jpg"
         },
         {
            "name":"Wookie Warrior",
            "subheader":"Enforcer",
            "imgUrl":"img/reinforcement/enforcer/wookie-warrior.jpg"
         },
         {
            "name":"Death Trooper",
            "subheader":"Enforcer",
            "imgUrl":"img/reinforcement/enforcer/death-trooper.jpg"
         },
         {
            "name":"Ovissian Gunner",
            "subheader":"Enforcer",
            "imgUrl":"img/reinforcement/enforcer/ovissian-gunner.png"
         },
         {
            "name":"FlameTrooper",
            "subheader":"Enforcer",
            "imgUrl":"img/reinforcement/enforcer/flame-trooper.jpg"
         },
         {
            "name":"B2-RP Rocket Droid",
            "subheader":"Aerial",
            "imgUrl":"img/reinforcement/aerial/b2-rp.jpg"
         },
         {
            "name":"Jet Trooper",
            "subheader":"Aerial",
            "imgUrl":"img/reinforcement/aerial/jet-trooper.jpg"
         },
         {
            "name":"Rebel Rocket Jumper",
            "subheader":"Aerial",
            "imgUrl":"img/reinforcement/aerial/rebel-rocket-jumper.jpg"
         },
         {
            "name":"Imperial Rocket Trooper",
            "subheader":"Aerial",
            "imgUrl":"img/reinforcement/aerial/imperial-rocket-trooper.jpg"
         },
         {
            "name":"Resistance Rocket Jumper",
            "subheader":"Aerial",
            "imgUrl":"img/reinforcement/aerial/resistance-rocket-jumper.jpg"
         },
         {
            "name":"First Order Jet Trooper",
            "subheader":"Aerial",
            "imgUrl":"img/reinforcement/aerial/first-order-jet-trooper.png"
         },
         {
            "name":"Ewok",
            "subheader":"Night Terror",
            "imgUrl":"https://starwarsblog.starwars.com/wp-content/uploads/2018/04/star-wars-battlefront-II-ewok-mode-tall.jpg",
            "availability":"unavailable",
            "alert":"ewok-hunt-only"
         }
      ],
      "trooper":[
         {
            "name":"Clone Trooper",
            "imgUrl":"img/trooper/assault/republic.jpg"
         },
         {
            "name":"Clone Heavy Trooper",
            "imgUrl":"img/trooper/heavy/republic.jpg"
         },
         {
            "name":"Clone Officer",
            "imgUrl":"img/trooper/officer/republic.jpg"
         },
         {
            "name":"Clone Specialist",
            "imgUrl":"img/trooper/specialist/republic.jpg"
         },
         {
            "name":"B1 Battle Droid",
            "imgUrl":"img/trooper/assault/separatist.jpg"
         },
         {
            "name":"B1 Heavy Battle Droid",
            "imgUrl":"img/trooper/heavy/separatist.jpg"
         },
         {
            "name":"OOM Command Battle Droid",
            "imgUrl":"img/trooper/officer/separatist.jpg"
         },
         {
            "name":"B1 Recon Droid",
            "imgUrl":"img/trooper/specialist/separatist.jpg"
         },
         {
            "name":"Rebel Soldier",
            "imgUrl":"img/trooper/assault/rebel.jpg"
         },
         {
            "name":"Rebel Heavy Soldier",
            "imgUrl":"img/trooper/heavy/rebel.jpg"
         },
         {
            "name":"Rebel Officer",
            "imgUrl":"img/trooper/officer/rebel.jpg"
         },
         {
            "name":"Rebel Sniper",
            "imgUrl":"img/trooper/specialist/rebel.jpg"
         },
         {
            "name":"Stormtrooper",
            "imgUrl":"img/trooper/assault/imperial.jpg"
         },
         {
            "name":"Heavy Stormtrooper",
            "imgUrl":"img/trooper/heavy/imperial.jpg"
         },
         {
            "name":"Imperial Officer",
            "imgUrl":"img/trooper/officer/imperial.jpg"
         },
         {
            "name":"Scout Trooper",
            "imgUrl":"img/trooper/specialist/imperial.jpg"
         },
         {
            "name":"Resistance Soldier",
            "imgUrl":"img/trooper/assault/resistance.jpg"
         },
         {
            "name":"Resistance Heavy Soldier",
            "imgUrl":"img/trooper/heavy/resistance.jpg"
         },
         {
            "name":"Resistance Officer",
            "imgUrl":"img/trooper/officer/resistance.jpg"
         },
         {
            "name":"Resistance Sniper",
            "imgUrl":"img/trooper/specialist/resistance.jpg"
         },
         {
            "name":"First Order Stormtrooper",
            "imgUrl":"img/trooper/assault/first-order.jpg"
         },
         {
            "name":"First Order Heavy Stormtrooper",
            "imgUrl":"img/trooper/heavy/first-order.jpg"
         },
         {
            "name":"First Order Officer",
            "imgUrl":"img/trooper/officer/first-order.jpg"
         },
         {
            "name":"First Order Specialist",
            "imgUrl":"img/trooper/specialist/first-order.jpg"
         }
      ]
   },
   "vehicles":[
      {
         "name":"AT-ST",
         "imgUrl":"img/vehicle/armor/at-st.jpg"
      },
      {
         "name":"First Order AT-ST",
         "imgUrl":"img/vehicle/armor/fo-at-st.jpg"
      },
      {
         "name":"TX-130",
         "imgUrl":"img/vehicle/armor/tx-130.jpg"
      },
      {
         "name":"AAT",
         "imgUrl":"img/vehicle/armor/aat.jpg"
      },
      {
         "name":"AT-RT",
         "imgUrl":"img/vehicle/armor/at-rt.jpg"
      },
      {
         "name":"Snowspeeder",
         "imgUrl":"img/vehicle/speeder/snowspeeder.jpg"
      },
      {
         "name":"BARC Speeder",
         "imgUrl":"img/vehicle/speeder/barc-speeder.jpg"
      },
      {
         "name":"LUUV",
         "imgUrl":"img/vehicle/speeder/luuv.jpg"
      },
      {
         "name":"X-34 Landspeeder",
         "imgUrl":"img/vehicle/speeder/x-34-landspeeder.jpg"
      },
      {
         "name":"Z4-7 Speeder Bike",
         "imgUrl":"img/vehicle/speeder/z4-7-speeder-bike.jpg"
      },
      {
         "name":"V-4X-D Ski Speeder",
         "imgUrl":"img/vehicle/speeder/v-4x-d-ski-speeder.jpg"
      },
      {
         "name":"STAP",
         "imgUrl":"img/vehicle/speeder/stap.jpg"
      },
      {
         "name":"MTT",
         "imgUrl":"img/vehicle/artillery/mtt.jpg"
      },
      {
         "name":"AT-AT",
         "imgUrl":"img/vehicle/artillery/at-at.jpg"
      },
      {
         "name":"AT-TE",
         "imgUrl":"img/vehicle/artillery/at-te.jpg"
      },
      {
         "name":"LAAT",
         "imgUrl":"img/vehicle/artillery/laat.jpg"
      },
      {
         "name":"U Wing",
         "imgUrl":"img/vehicle/artillery/u-wing.jpg"
      }
   ],
   "starfighters":{
      "hero-starfighter":[
         {
            "name":"Boba Fett",
            "subheader":"Slave I",
            "imgUrl":"img/hero-starfighter/boba-fett-slave-1.jpg"
         },
         {
            "name":"Darth Maul",
            "subheader":"Scimitar",
            "imgUrl":"img/hero-starfighter/darth-maul-scimitar.jpg"
         },
         {
            "name":"Darth Vader",
            "subheader":"TIE Advanced X1",
            "imgUrl":"img/hero-starfighter/darth-vader-tie-advanced-x1.jpg"
         },
         {
            "name":"Han & Chewbacca",
            "subheader":"Millenium Falcon",
            "imgUrl":"img/hero-starfighter/han-chewbacca-falcon.jpg"
         },
         {
            "name":"Iden Versio",
            "subheader":"TIE Fighter",
            "imgUrl":"img/hero-starfighter/iden-versio-tie-ln-fighter.jpg"
         },
         {
            "name":"Kylo Ren",
            "subheader":"TIE Silencer",
            "imgUrl":"img/hero-starfighter/kylo-ren-tie-silencer.jpg"
         },
         {
            "name":"Lando & L3-37",
            "subheader":"Millenium Falcon",
            "imgUrl":"img/hero-starfighter/lando-l3-37-falcon.jpg"
         },
         {
            "name":"Luke Skywalker",
            "subheader":"T-65B X-Wing",
            "imgUrl":"img/hero-starfighter/luke-t-65bx-wing.jpg"
         },
         {
            "name":"Poe Dameron",
            "subheader":"T-70 X-Wing",
            "imgUrl":"img/hero-starfighter/poe-dameron-t-70-x-wing.jpg"
         },
         {
            "name":"Rey & Chewbacca",
            "subheader":"Millenium Falcon",
            "imgUrl":"img/hero-starfighter/rey-chewbacca-falcon.jpg"
         },
         {
            "name":"Tallie Lintra",
            "subheader":"RZ-2 A-Wing",
            "imgUrl":"img/hero-starfighter/tallie-lintra-rz-2-a-wing.jpg"
         },
         {
            "name":"Yoda",
            "subheader":"Actis Class Light Interceptor",
            "imgUrl":"img/hero-starfighter/yoda-actis-class-light-interceptor.jpg"
         }
      ],
      "starfighter":[
         {
            "name":"ARC-170 Starfighter",
            "subheader":"Fighter",
            "imgUrl":"img/starfighter/fighter/arc-170-starfighter.jpg"
         },
         {
            "name":"N1 Naboo Starfighter",
            "subheader":"Fighter",
            "imgUrl":"img/starfighter/fighter/n1-naboo-starfighter.jpg"
         },
         {
            "name":"Vulture Droid",
            "subheader":"Fighter",
            "imgUrl":"img/starfighter/fighter/vulture.jpg"
         },
         {
            "name":"TIE Fighter ",
            "subheader":"Fighter",
            "imgUrl":"img/starfighter/fighter/tie-ln-fighter.jpg"
         },
         {
            "name":"X-Wing",
            "subheader":"Fighter",
            "imgUrl":"img/starfighter/fighter/x-wing.jpg"
         },
         {
            "name":"Droid Tri-Fighter",
            "subheader":"Interceptor",
            "imgUrl":"img/starfighter/interceptor/droid-tri-fighter.jpg"
         },
         {
            "name":"R-Z1 A-Wing",
            "subheader":"Interceptor",
            "imgUrl":"img/starfighter/interceptor/rz-1-a-wing.jpg"
         },
         {
            "name":"R-Z2 A-Wing",
            "subheader":"Interceptor",
            "imgUrl":"img/starfighter/interceptor/r-z2-a-wing.jpg"
         },
         {
            "name":"TIE Interceptor",
            "subheader":"Interceptor",
            "imgUrl":"img/starfighter/interceptor/tie-in-interceptor.jpg"
         },
         {
            "name":"TIE/SF",
            "subheader":"Interceptor",
            "imgUrl":"img/starfighter/interceptor/tie-sf.jpg"
         },
         {
            "name":"V-Wing",
            "subheader":"Interceptor",
            "imgUrl":"img/starfighter/interceptor/v-wing.jpg"
         },
         {
            "name":"TIE SA Bomber",
            "subheader":"Bomber",
            "imgUrl":"img/starfighter/bomber/tie-sa-bomber.jpg"
         },
         {
            "name":"Hyena Class Bomber",
            "subheader":"Bomber",
            "imgUrl":"img/starfighter/bomber/hyena-class-bomber.jpg"
         },
         {
            "name":"BTL-A4 Y-Wing",
            "subheader":"Bomber",
            "imgUrl":"img/starfighter/bomber/btl-a4-y-wing.jpg"
         },
         {
            "name":"BTL-B Y-Wing",
            "subheader":"Bomber",
            "imgUrl":"img/starfighter/bomber/btl-b-y-wing.jpg"
         }
      ]
   },
   "weapons":{
      "assault-weapon":[
         {
            "name":"DC-15A",
            "imgUrl":"img/weapon/assault-weapon/dc-15a.png",
            "summary":{
               "factions":[
                  "faction/republic"
               ]
            }
         },
         {
            "name":"E-5",
            "imgUrl":"img/weapon/assault-weapon/e-5.png",
            "summary":{
               "factions":[
                  "faction/separatists"
               ]
            }
         },
         {
            "name":"A280C",
            "imgUrl":"img/weapon/assault-weapon/a280c.png",
            "summary":{
               "factions":[
                  "faction/rebels"
               ]
            }
         },
         {
            "name":"E-11",
            "imgUrl":"img/weapon/assault-weapon/e-11.png",
            "summary":{
               "factions":[
                  "faction/empire"
               ]
            }
         },
         {
            "name":"EL-16",
            "imgUrl":"img/weapon/assault-weapon/el-16.png",
            "summary":{
               "factions":[
                  "faction/resistance"
               ]
            }
         },
         {
            "name":"F-11D",
            "imgUrl":"img/weapon/assault-weapon/f-11d.png",
            "summary":{
               "factions":[
                  "faction/first-order"
               ]
            }
         },
         {
            "name":"A280",
            "imgUrl":"img/weapon/assault-weapon/a280.png",
            "summary":{
               "factions":[
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         },
         {
            "name":"CR-2",
            "imgUrl":"img/weapon/assault-weapon/cr-2.png",
            "summary":{
               "factions":[
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         },
         {
            "name":"EL-16HFE",
            "imgUrl":"img/weapon/assault-weapon/el-16hfe.png",
            "summary":{
               "factions":[
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         }
      ],
      "heavy-weapon":[
         {
            "name":"DC-15",
            "summary":{
               "factions":[
                  "faction/republic"
               ]
            }
         },
         {
            "name":"E-5C",
            "summary":{
               "factions":[
                  "faction/separatists"
               ]
            }
         },
         {
            "name":"RT-97C",
            "summary":{
               "factions":[
                  "faction/rebels"
               ]
            }
         },
         {
            "name":"DLT-19",
            "summary":{
               "factions":[
                  "faction/empire"
               ]
            }
         },
         {
            "name":"M-45",
            "summary":{
               "factions":[
                  "faction/resistance"
               ]
            }
         },
         {
            "name":"FWMB-10",
            "summary":{
               "factions":[
                  "faction/first-order"
               ]
            }
         },
         {
            "name":"DC-15LE",
            "summary":{
               "factions":[
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         },
         {
            "name":"FWMB10",
            "summary":{
               "factions":[
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         },
         {
            "name":"TL-50 Heavy Repeater",
            "summary":{
               "factions":[
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         }
      ],
      "officer-weapon":[
         {
            "name":"DC-17",
            "summary":{
               "factions":[
                  "faction/republic"
               ]
            }
         },
         {
            "name":"RG-4D",
            "summary":{
               "factions":[
                  "faction/separatists"
               ]
            }
         },
         {
            "name":"DH-17",
            "summary":{
               "factions":[
                  "faction/rebels"
               ]
            }
         },
         {
            "name":"RK-3",
            "summary":{
               "factions":[
                  "faction/empire"
               ]
            }
         },
         {
            "name":"GLIE-44",
            "summary":{
               "factions":[
                  "faction/resistance"
               ]
            }
         },
         {
            "name":"SE-44",
            "summary":{
               "factions":[
                  "faction/first-order"
               ]
            }
         },
         {
            "name":"Blurrg-1120",
            "summary":{
               "factions":[
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         },
         {
            "name":"S-5",
            "summary":{
               "factions":[
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         },
         {
            "name":"SE-44C",
            "summary":{
               "factions":[
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         }
      ],
      "specialist-weapon":[
         {
            "name":"Valken-38X",
            "summary":{
               "factions":[
                  "faction/republic"
               ]
            }
         },
         {
            "name":"E-5S",
            "summary":{
               "factions":[
                  "faction/separatists"
               ]
            }
         },
         {
            "name":"DLT-20A",
            "summary":{
               "factions":[
                  "faction/rebels"
               ]
            }
         },
         {
            "name":"DLT-19X",
            "summary":{
               "factions":[
                  "faction/empire"
               ]
            }
         },
         {
            "name":"A180-Sniper",
            "summary":{
               "factions":[
                  "faction/resistance"
               ]
            }
         },
         {
            "name":"DLT-19D",
            "summary":{
               "factions":[
                  "faction/first-order"
               ]
            }
         },
         {
            "name":"A280-CFE",
            "summary":{
               "factions":[
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         },
         {
            "name":"IQA-11",
            "summary":{
               "factions":[
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         },
         {
            "name":"NT-242",
            "summary":{
               "factions":[
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         }
      ],
      "reinforcement-weapon":[

      ],
      "starcard-weapon":[

      ],
      "hero-weapon":[

      ]
   },
   "rumours":{
      "hero":[
         {
            "name":"Ahsoka Tano",
            "subheader":"Jedi Padawan",
            "imgUrl":"img/rumour/hero/ahsoka-tano.png",
            "summary":{
               "rumours/leaks":"Some_Info",
               "rumours/datamines":"Referenced in voicelines"
            }
         },
         {
            "name":"Padme Amidala",
            "subheader":"Senator",
            "imgUrl":"img/rumour/hero/padme-amidala.jpg",
            "summary":{
               "rumours/datamines":"Referenced in voicelines"
            }
         },
         {
            "name":"Asajj Ventress",
            "subheader":"Nightsister",
            "imgUrl":"img/rumour/hero/asajj-ventress.jpg",
            "summary":{
               "rumours/leaks":"Some_Info"
            }
         }
      ],
      "reinforcement":[
         {
            "name":"ISB Officer",
            "imgUrl":"",
            "summary":{
               "rumours/datamines":"Text Reference, Possible Animations"
            }
         },
         {
            "name":"Ewok",
            "imgUrl":"https://starwarsblog.starwars.com/wp-content/uploads/2018/04/star-wars-battlefront-II-ewok-mode-tall.jpg",
            "summary":{
               "rumours      /datamines":"New Animations, 'Ewok Bow' Weapon"
            }
         }
      ]
   }
}