data={ 
   "locations":[ 
      { 
         "name":"Ajan Kloss",
         "imgUrl":"https://vignette.wikia.nocookie.net/battlefront/images/0/0a/Trospromo1.jpg/revision/latest",
         "summary":{ 
            "maps":1,
            "online-modes":[ 
               "mode/capital-supremacy",
               "mode/co-op"
            ],
            "offline-modes":[ 

            ]
         }
      },
      { 
         "name":"Bespin",
         "imgUrl":"https://cdnb.artstation.com/p/assets/covers/images/004/237/685/large/daniel-cambrand-danielcambrand-03.jpg",
         "summary":{ 
            "maps":1,
            "online-modes":[ 
               "mode/blast",
               "mode/hvv"
            ],
            "offline-modes":[ 
               "mode/campaign",
               "mode/team-battle",
               "mode/onslaught",
               "mode/duel"
            ]
         }
      },
      { 
         "name":"Crait",
         "imgUrl":"https://cdna.artstation.com/p/assets/images/images/009/728/722/large/mikael-andersson-swbfii-mikaelandersson-28.jpg?1520549861",
         "summary":{ 
            "maps":1,
            "online-modes":[ 
               "mode/blast",
               "mode/galactic-assault"
            ],
            "offline-modes":[ 
               "mode/onslaught",
               "mode/team-battle",
               "mode/duel"
            ]
         }
      },
      { 
         "name":"Death Star II",
         "imgUrl":"img/location/death-star-ii.jpg",
         "summary":{ 
            "maps":1,
            "online-modes":[ 
               "mode/blast",
               "mode/galactic-assault",
               "mode/hero-showdown",
               "mode/hvv",
               "mode/strike"
            ],
            "offline-modes":[ 
               "mode/onslaught",
               "mode/team-battle",
               "mode/duel"
            ]
         }
      },
      { 
         "name":"Dreadnought",
         "imgUrl":"https://cdna.artstation.com/p/assets/images/images/020/328/558/large/saralie-wagstrom-swbf-saraliewagstrom-06.jpg?1567361315",
         "summary":{ 
            "maps":1,
            "online-modes":[ 
               "mode/capital-supremacy",
               "mode/hvv"
            ],
            "offline-modes":[ 

            ]
         }
      },
      { 
         "name":"Endor",
         "imgUrl":"https://media.contentapi.ea.com/content/legacy/starwars-ea-com/es_MX/starwars/battlefront/news-articles/the-star-wars-battlefront-planets--creating-endor/_jcr_content/featuredImage/renditions/rendition1.img.jpg",
         "summary":{ 
            "maps":2,
            "online-modes":[ 
               "mode/blast",
               "mode/ewok-hunt",
               "mode/galactic-assault",
               "mode/hero-showdown",
               "mode/hvv",
               "mode/strike"
            ],
            "offline-modes":[ 
               "mode/campaign",
               "mode/onslaught",
               "mode/team-battle",
               "mode/duel"
            ]
         }
      },
      { 
         "name":"Felucia",
         "imgUrl":"https://cdn.wccftech.com/wp-content/uploads/2019/09/swbfII_clone_commando.jpg",
         "summary":{ 
            "maps":1,
            "online-modes":[ 
               "mode/capital-supremacy",
               "mode/co-op"
            ],
            "offline-modes":[ 
               "mode/instant-action"
            ]
         }
      },
      { 
         "name":"Geonosis",
         "imgUrl":"https://cdnb.artstation.com/p/assets/images/images/014/320/967/large/pontus-ryman-swbfii-pontusryman-07.jpg?1543483500",
         "summary":{ 
            "maps":2,
            "online-modes":[ 
               "mode/blast",
               "mode/capital-supremacy",
               "mode/co-op",
               "mode/galactic-assault",
               "mode/hvv"
            ],
            "offline-modes":[ 
               "mode/instant-action",
               "mode/onslaught",
               "mode/team-battle",
               "mode/duel"
            ]
         }
      },
      { 
         "name":"Hoth",
         "imgUrl":"https://lumiere-a.akamaihd.net/v1/images/Hoth_d074d307.jpeg",
         "summary":{ 
            "maps":1,
            "online-modes":[ 
               "mode/blast",
               "mode/galactic-assault",
               "mode/hero-showdown",
               "mode/hvv",
               "mode/strike"
            ],
            "offline-modes":[ 
               "mode/onslaught",
               "mode/team-battle",
               "mode/duel"
            ]
         }
      },
      { 
         "name":"Jakku",
         "imgUrl":"https://cdna.artstation.com/p/assets/images/images/009/033/696/large/anton-kavousi-swbfii-antonkavousi-03.jpg?1516747707",
         "summary":{ 
            "maps":1,
            "online-modes":[ 
               "mode/blast",
               "mode/galactic-assault",
               "mode/hero-showdown",
               "mode/hvv",
               "mode/strike"
            ],
            "offline-modes":[ 
               "mode/campaign",
               "mode/onslaught",
               "mode/team-battle",
               "mode/duel"
            ]
         }
      },
      { 
         "name":"Kamino",
         "imgUrl":"https://vignette.wikia.nocookie.net/battlefront/images/d/d1/Kamino_Facility_Andrew_Hamilton.jpg/revision/latest?cb=20180308210107",
         "summary":{ 
            "maps":1,
            "online-modes":[ 
               "mode/blast",
               "mode/capital-supremacy",
               "mode/co-op",
               "mode/galactic-assault",
               "mode/hero-showdown",
               "mode/hvv",
               "mode/strike"
            ],
            "offline-modes":[ 
               "mode/battle-scenarios",
               "mode/instant-action",
               "mode/onslaught",
               "mode/team-battle",
               "mode/duel"
            ]
         }
      },
      { 
         "name":"Kashyyyk",
         "imgUrl":"https://i.redd.it/vocninji9jt11.jpg",
         "summary":{ 
            "maps":2,
            "online-modes":[ 
               "mode/blast",
               "mode/capital-supremacy",
               "mode/co-op",
               "mode/galactic-assault",
               "mode/hero-showdown",
               "mode/hvv",
               "mode/strike"
            ],
            "offline-modes":[ 
               "mode/instant-action",
               "mode/onslaught",
               "mode/team-battle",
               "mode/duel"
            ]
         }
      },
      { 
         "name":"Kessel",
         "imgUrl":"https://cdna.artstation.com/p/assets/images/images/013/864/392/large/michael-anderson-swbfii-michaelanderson-21.jpg?1541431881",
         "summary":{ 
            "maps":1,
            "online-modes":[ 
               "mode/blast",
               "mode/hero-showdown",
               "mode/hvv",
               "mode/strike"
            ],
            "offline-modes":[ 
               "mode/onslaught",
               "mode/team-battle",
               "mode/duel"
            ]
         }
      },
      { 
         "name":"MC85 Star Cruiser",
            "imgUrl":"img/location/mc85-star-cruiser.jpg",
         "summary":{ 
            "maps":1,
            "online-modes":[ 
               "mode/capital-supremacy"
            ],
            "offline-modes":[ 

            ]
         }
      },
      { 
         "name":"Naboo",
         "imgUrl":"https://vignette.wikia.nocookie.net/battlefront/images/7/79/Naboo_Theed_-_Royal_Palace_%281%29_-_Mikael_Andersson_DICE.jpg",
         "summary":{ 
            "maps":2,
            "online-modes":[ 
               "mode/blast",
               "mode/capital-supremacy",
               "mode/co-op",
               "mode/galactic-assault",
               "mode/hero-showdown",
               "mode/hvv",
               "mode/strike"
            ],
            "offline-modes":[ 
               "mode/battle-scenarios",
               "mode/campaign",
               "mode/instant-action",
               "mode/onslaught",
               "mode/team-battle",
               "mode/duel"
            ]
         }
      },
      { 
         "name":"Pillio",
         "imgUrl":"https://vignette.wikia.nocookie.net/battlefront/images/e/e1/SWB2-The_Observatory.jpg/revision/latest?cb=20171202012804",
         "availability":"unavailable",
         "alert":"campaign-only"
      },
      { 
         "name":"Resurgent-Class Star Destroyer",
            "imgUrl":"img/location/resurgent-class-star-destroyer.jpg",
         "summary":{ 
            "maps":1,
            "online-modes":[ 
               "mode/capital-supremacy"
            ],
            "offline-modes":[ 

            ]
         }
      },
      { 
         "name":"Scarif",
            "imgUrl":"img/location/scarif.png",
         "summary":{ 
            "maps":2,
            "online-modes":[ 
               "mode/capital-supremacy",
               "mode/co-op"
            ],
            "offline-modes":[ 
               "mode/campaign",
               "mode/instant-action"
            ]
         }
      },
      { 
         "name":"Starkiller Base",
         "imgUrl":"https://cdna.artstation.com/p/assets/images/images/010/231/578/large/marcus-fritze-swbfii-marcusfritze-18.jpg?1523305576",
         "summary":{ 
            "maps":1,
            "online-modes":[ 
               "mode/blast",
               "mode/galactic-assault",
               "mode/hero-showdown",
               "mode/hvv",
               "mode/strike"
            ],
            "offline-modes":[ 
               "mode/battle-scenarios",
               "mode/campaign",
               "mode/onslaught",
               "mode/team-battle",
               "mode/duel",
               "mode/tutorial"
            ]
         }
      },
      { 
         "name":"Sullust",
         "imgUrl":"https://vignette.wikia.nocookie.net/battlefront/images/5/56/SWB2-Cache_Grab.jpg",
         "availability":"unavailable",
         "alert":"campaign-only"
      },
      { 
         "name":"Takodana",
         "imgUrl":"https://cdnb.artstation.com/p/assets/images/images/009/707/633/large/daniel-rocque-swbfii-danielrocquebengtsson-02.jpg?1520445639",
         "summary":{ 
            "maps":1,
            "online-modes":[ 
               "mode/blast",
               "mode/galactic-assault",
               "mode/hero-showdown",
               "mode/hvv",
               "mode/strike"
            ],
            "offline-modes":[ 
               "mode/battle-scenarios",
               "mode/campaign",
               "mode/onslaught",
               "mode/team-battle",
               "mode/duel"
            ]
         }
      },
      { 
         "name":"Tatooine",
         "imgUrl":"https://vignette.wikia.nocookie.net/battlefront/images/d/d9/Mos_Eisley_View.jpg/revision/latest?cb=20180307193130",
         "summary":{ 
            "maps":2,
            "online-modes":[ 
               "mode/blast",
               "mode/galactic-assault",
               "mode/hero-showdown",
               "mode/hvv",
               "mode/strike"
            ],
            "offline-modes":[ 
               "mode/battle-scenarios",
               "mode/onslaught",
               "mode/team-battle",
               "mode/duel"
            ]
         }
      },
      { 
         "name":"Vardos",
         "imgUrl":"https://vignette.wikia.nocookie.net/battlefront/images/c/c7/SWB2-Art-Vardos.jpg/revision/latest?cb=20171202011459",
         "availability":"unavailable",
         "alert":"campaign-only"
      },
      { 
         "name":"Venator",
         "imgUrl":"https://images3.alphacoders.com/883/883581.png",
         "summary":{ 
            "maps":1,
            "online-modes":[ 
               "mode/capital-supremacy",
               "mode/hvv"
            ],
            "offline-modes":[ 

            ]
         }
      },
      { 
         "name":"Yavin 4",
         "imgUrl":"https://i.redd.it/ig9ectnjbgsz.jpg",
         "summary":{ 
            "maps":1,
            "online-modes":[ 
               "mode/blast",
               "mode/galactic-assault",
               "mode/hero-showdown",
               "mode/hvv",
               "mode/strike"
            ],
            "offline-modes":[ 
               "mode/battle-scenarios",
               "mode/onslaught",
               "mode/team-battle",
               "mode/duel"
            ]
         }
      }
   ],
   "characters":{ 
      "hero":[ 
         { 
            "name":"Anakin Skywalker",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/anakin/hero/anakin-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/republic"
               ]
            }
         },
         { 
            "name":"BB-8",
            "imgUrl":"img/hero/bb-8.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/resistance"
               ]
            }
         },
         { 
            "name":"BB-9E",
            "imgUrl":"img/hero/bb-9e.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/first-order"
               ]
            }
         },
         { 
            "name":"Boba Fett",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/boba-fett/hero-images/boba-fett-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/empire"
               ]
            }
         },
         { 
            "name":"Bossk",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/bossk/hero/bossk-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/separatists",
                  "faction/empire"
               ]
            }
         },
         { 
            "name":"Captain Phasma",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/phasma/hero/phasma-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/first-order"
               ]
            }
         },
         { 
            "name":"Chewbacca",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/chewbacca/hero/chewie-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/rebels",
                  "faction/republic"
               ]
            }
         },
         { 
            "name":"Count Dooku",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/count-dooku/hero/dooku-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/separatists"
               ]
            }
         },
         { 
            "name":"Darth Maul",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/darth-maul/hero-images/darth-maul-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/separatists"
               ]
            }
         },
         { 
            "name":"Darth Vader",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/darth-vader/hero-images/darth-vader-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/empire"
               ]
            }
         },
         { 
            "name":"Emperor Palpatine",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/emperor/hero/emporer-palpatine-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/empire"
               ]
            }
         },
         { 
            "name":"Finn",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/finn/hero/finn-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/resistance"
               ]
            }
         },
         { 
            "name":"General Greivous",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/grievous/hero/grievous-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/separatists"
               ]
            }
         },
         { 
            "name":"Han Solo",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/han-solo/hero-images/han-solo-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/rebels"
               ]
            }
         },
         { 
            "name":"Iden Versio",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/iden/hero/iden-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/empire"
               ]
            }
         },
         { 
            "name":"Kylo Ren",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/kylo-ren/hero/kylo-ren-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/first-order"
               ]
            }
         },
         { 
            "name":"Lando Calrissian",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/lando/hero/lando-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/rebels"
               ]
            }
         },
         { 
            "name":"Leia Organa",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/leia/hero/leia-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/rebels"
               ]
            }
         },
         { 
            "name":"Luke Skywalker",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/luke/hero/luke-skywalker-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/rebels"
               ]
            }
         },
         { 
            "name":"Obi-Wan Kenobi",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/obi-wan/hero/obi-wan-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/republic"
               ]
            }
         },
         { 
            "name":"Rey",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/rey/hero-images/rey-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/resistance"
               ]
            }
         },
         { 
            "name":"Yoda",
            "imgUrl":"https://media.contentapi.ea.com/content/dam/ea/walrus/characters/yoda/hero-images/yoda-hero-lg.jpg",
            "summary":{ 
               "factions":[ 
                  "faction/republic"
               ]
            }
         }
      ],
      "reinforcement":[ 
         { 
            "name":"ARC Trooper",
            "imgUrl":"img/reinforcement/infiltrator/arc-trooper.jpg"
         },
         { 
            "name":"Commando Droid",
            "imgUrl":"img/reinforcement/infiltrator/commando-droid.jpg"
         },
         { 
            "name":"Caphex Spy",
            "imgUrl":"img/reinforcement/infiltrator/caphex-spy.png"
         },
         { 
            "name":"Sith Trooper",
            "imgUrl":"img/reinforcement/infiltrator/sith-trooper.jpg"
         },
         { 
            "name":"Clone Commando",
            "imgUrl":"img/reinforcement/enforcer/clone-commando.jpg"
         },
         { 
            "name":"Droideka",
            "imgUrl":"img/reinforcement/enforcer/droideka.jpg"
         },
         { 
            "name":"B2 Battle Droid",
            "imgUrl":"img/reinforcement/enforcer/b2-battle-droid.jpg"
         },
         { 
            "name":"Wookie Warrior",
            "imgUrl":"img/reinforcement/enforcer/wookie-warrior.jpg"
         },
         { 
            "name":"Death Trooper",
            "imgUrl":"img/reinforcement/enforcer/death-trooper.jpg"
         },
         { 
            "name":"Ovissian Gunner",
            "imgUrl":"img/reinforcement/enforcer/ovissian-gunner.png"
         },
         { 
            "name":"FlameTrooper",
            "imgUrl":"img/reinforcement/enforcer/flame-trooper.jpg"
         },
         { 
            "name":"B2-RP Rocket Droid",
            "imgUrl":"img/reinforcement/aerial/b2-rp.jpg"
         },
         { 
            "name":"Jet Trooper",
            "imgUrl":"img/reinforcement/aerial/jet-trooper.jpg"
         },
         { 
            "name":"Rebel Rocket Jumper",
            "imgUrl":"img/reinforcement/aerial/rebel-rocket-jumper.jpg"
         },
         { 
            "name":"Imperial Rocket Trooper",
            "imgUrl":"img/reinforcement/aerial/imperial-rocket-trooper.jpg"
         },
         { 
            "name":"Resistance Rocket Jumper",
            "imgUrl":"img/reinforcement/aerial/resistance-rocket-jumper.jpg"
         },
         { 
            "name":"First Order Jet Trooper",
            "imgUrl":"img/reinforcement/aerial/first-order-jet-trooper.png"
         },
         { 
            "name":"Ewok",
            "imgUrl":"https://starwarsblog.starwars.com/wp-content/uploads/2018/04/star-wars-battlefront-II-ewok-mode-tall.jpg"
         }
      ],
      "trooper":[ 
         { 
            "name":"Clone Trooper",
            "imgUrl":"img/trooper/assault/republic.jpg"
         },
         { 
            "name":"Clone Heavy Trooper",
            "imgUrl":"img/trooper/heavy/republic.jpg"
         },
         { 
            "name":"Clone Officer",
            "imgUrl":"img/trooper/officer/republic.jpg"
         },
         { 
            "name":"Clone Specialist",
            "imgUrl":"img/trooper/specialist/republic.jpg"
         },
         { 
            "name":"B1 Battle Droid",
            "imgUrl":"img/trooper/assault/separatist.jpg"
         },
         { 
            "name":"B1 Heavy Battle Droid",
            "imgUrl":"img/trooper/heavy/separatist.jpg"
         },
         { 
            "name":"OOM Command Battle Droid",
            "imgUrl":"img/trooper/officer/separatist.jpg"
         },
         { 
            "name":"B1 Recon Droid",
            "imgUrl":"img/trooper/specialist/separatist.jpg"
         },
         { 
            "name":"Rebel Soldier",
            "imgUrl":"img/trooper/assault/rebel.jpg"
         },
         { 
            "name":"Rebel Heavy Soldier",
            "imgUrl":"img/trooper/heavy/rebel.jpg"
         },
         { 
            "name":"Rebel Officer",
            "imgUrl":"img/trooper/officer/rebel.jpg"
         },
         { 
            "name":"Rebel Sniper",
            "imgUrl":"img/trooper/specialist/rebel.jpg"
         },
         { 
            "name":"Stormtrooper",
            "imgUrl":"img/trooper/assault/imperial.jpg"
         },
         { 
            "name":"Heavy Stormtrooper",
            "imgUrl":"img/trooper/heavy/imperial.jpg"
         },
         { 
            "name":"Imperial Officer",
            "imgUrl":"img/trooper/officer/imperial.jpg"
         },
         { 
            "name":"Scout Trooper",
            "imgUrl":"img/trooper/specialist/imperial.jpg"
         },
         { 
            "name":"Resistance Soldier",
            "imgUrl":"img/trooper/assault/resistance.jpg"
         },
         { 
            "name":"Resistance Heavy Soldier",
            "imgUrl":"img/trooper/heavy/resistance.jpg"
         },
         { 
            "name":"Resistance Officer",
            "imgUrl":"img/trooper/officer/resistance.jpg"
         },
         { 
            "name":"Resistance Sniper",
            "imgUrl":"img/trooper/specialist/resistance.jpg"
         },
         { 
            "name":"First Order Stormtrooper",
            "imgUrl":"img/trooper/assault/first-order.jpg"
         },
         { 
            "name":"First Order Heavy Stormtrooper",
            "imgUrl":"img/trooper/heavy/first-order.jpg"
         },
         { 
            "name":"First Order Officer",
            "imgUrl":"img/trooper/officer/first-order.jpg"
         },
         { 
            "name":"First Order Specialist",
            "imgUrl":"img/trooper/specialist/first-order.jpg"
         }
      ]
   },
   "vehicles":[ 
      { 
         "name":"AT-ST",
         "imgUrl":"img/vehicle/armor/at-st.jpg"
      },
      { 
         "name":"First Order AT-ST",
         "imgUrl":"img/vehicle/armor/fo-at-st.jpg"
      },
      { 
         "name":"TX-130",
         "imgUrl":"img/vehicle/armor/tx-130.jpg"
      },
      { 
         "name":"AAT",
         "imgUrl":"img/vehicle/armor/aat.jpg"
      },
      { 
         "name":"AT-RT",
         "imgUrl":"img/vehicle/armor/at-rt.jpg"
      },
      { 
         "name":"Snowspeeder",
         "imgUrl":"img/vehicle/speeder/snowspeeder.jpg"
      },
      { 
         "name":"BARC Speeder",
         "imgUrl":"img/vehicle/speeder/barc-speeder.jpg"
      },
      { 
         "name":"LUUV",
         "imgUrl":"img/vehicle/speeder/luuv.jpg"
      },
      { 
         "name":"X-34 Landspeeder",
         "imgUrl":"img/vehicle/speeder/x-34-landspeeder.jpg"
      },
      { 
         "name":"Z4-7 Speeder Bike",
         "imgUrl":"img/vehicle/speeder/z4-7-speeder-bike.jpg"
      },
      { 
         "name":"V-4X-D Ski Speeder",
         "imgUrl":"img/vehicle/speeder/v-4x-d-ski-speeder.jpg"
      },
      { 
         "name":"STAP",
         "imgUrl":"img/vehicle/speeder/stap.jpg"
      },
      { 
         "name":"MTT",
         "imgUrl":"img/vehicle/artillery/mtt.jpg"
      },
      { 
         "name":"AT-AT",
         "imgUrl":"img/vehicle/artillery/at-at.jpg"
      },
      { 
         "name":"AT-TE",
         "imgUrl":"img/vehicle/artillery/at-te.jpg"
      },
      { 
         "name":"LAAT",
         "imgUrl":"img/vehicle/artillery/laat.jpg"
      },
      { 
         "name":"U Wing",
         "imgUrl":"img/vehicle/artillery/u-wing.jpg"
      }
   ],
   "starfighters":{ 
      "hero-starfighter":[ 
         { 
            "name":"Boba Fett (Slave I)",
            "imgUrl":"img/hero-starfighter/boba-fett-slave-1.jpg"
         },
         { 
            "name":"Darth Maul (Scimitar)",
            "imgUrl":"img/hero-starfighter/darth-maul-scimitar.jpg"
         },
         { 
            "name":"Darth Vader (TIE Advanced X1)",
            "imgUrl":"img/hero-starfighter/darth-vader-tie-advanced-x1.jpg"
         },
         { 
            "name":"Han & Chewbacca (Millenium Falcon)",
            "imgUrl":"img/hero-starfighter/han-chewbacca-falcon.jpg"
         },
         { 
            "name":"Iden Versio (TIE Fighter)",
            "imgUrl":"img/hero-starfighter/iden-versio-tie-ln-fighter.jpg"
         },
         { 
            "name":"Kylo Ren (TIE Silencer)",
            "imgUrl":"img/hero-starfighter/kylo-ren-tie-silencer.jpg"
         },
         { 
            "name":"Lando & L3-37 (Millenium Falcon)",
            "imgUrl":"img/hero-starfighter/lando-l3-37-falcon.jpg"
         },
         { 
            "name":"Luke Skywalker (T-65B X-Wing)",
            "imgUrl":"img/hero-starfighter/luke-t-65bx-wing.jpg"
         },
         { 
            "name":"Poe Dameron (T-70 X-Wing)",
            "imgUrl":"img/hero-starfighter/poe-dameron-t-70-x-wing.jpg"
         },
         { 
            "name":"Rey & Chewbacca (Millenium Falcon)",
            "imgUrl":"img/hero-starfighter/rey-chewbacca-falcon.jpg"
         },
         { 
            "name":"Tallie Lintra (RZ-2 A-Wing)",
            "imgUrl":"img/hero-starfighter/tallie-lintra-rz-2-a-wing.jpg"
         },
         { 
            "name":"Yoda (Actis Class Light Interceptor)",
            "imgUrl":"img/hero-starfighter/yoda-actis-class-light-interceptor.jpg"
         }
      ],
      "starfighter":[ 
         { 
            "name":"ARC-170 Starfighter",
            "imgUrl":"img/starfighter/fighter/arc-170-starfighter.jpg"
         },
         { 
            "name":"N1 Naboo Starfighter",
            "imgUrl":"img/starfighter/fighter/n1-naboo-starfighter.jpg"
         },
         { 
            "name":"Vulture Droid",
            "imgUrl":"img/starfighter/fighter/vulture.jpg"
         },
         { 
            "name":"TIE Fighter ",
            "imgUrl":"img/starfighter/fighter/tie-ln-fighter.jpg"
         },
         { 
            "name":"X-Wing",
            "imgUrl":"img/starfighter/fighter/x-wing.jpg"
         },
         { 
            "name":"Droid Tri-Fighter",
            "imgUrl":"img/starfighter/interceptor/droid-tri-fighter.jpg"
         },
         { 
            "name":"R-Z1 A-Wing",
            "imgUrl":"img/starfighter/interceptor/rz-1-a-wing.jpg"
         },
         { 
            "name":"R-Z2 A-Wing",
            "imgUrl":"img/starfighter/interceptor/r-z2-a-wing.jpg"
         },
         { 
            "name":"TIE Interceptor",
            "imgUrl":"img/starfighter/interceptor/tie-in-interceptor.jpg"
         },
         { 
            "name":"TIE/SF",
            "imgUrl":"img/starfighter/interceptor/tie-sf.jpg"
         },
         { 
            "name":"V-Wing",
            "imgUrl":"img/starfighter/interceptor/v-wing.jpg"
         },
         { 
            "name":"TIE SA Bomber",
            "imgUrl":"img/starfighter/bomber/tie-sa-bomber.jpg"
         },
         { 
            "name":"Hyena Class Bomber",
            "imgUrl":"img/starfighter/bomber/hyena-class-bomber.jpg"
         },
         { 
            "name":"BTL-A4 Y-Wing",
            "imgUrl":"img/starfighter/bomber/btl-a4-y-wing.jpg"
         },
         { 
            "name":"BTL-B Y-Wing",
            "imgUrl":"img/starfighter/bomber/btl-b-y-wing.jpg"
         }
      ]
   },
   "weapons":{ 
      "assault-weapon":[ 
         { 
            "name":"DC-15A",
			"imgUrl": "img/weapon/assault-weapon/dc-15a.png",
            "summary":{ 
               "factions":[ 
                  "faction/republic"
               ]
            }
         },
         { 
            "name":"E-5",
			"imgUrl": "img/weapon/assault-weapon/e-5.png",
            "summary":{ 
               "factions":[ 
                  "faction/separatists"
               ]
            }
         },
         { 
            "name":"A280C",
			"imgUrl": "img/weapon/assault-weapon/a280c.png",
            "summary":{ 
               "factions":[ 
                  "faction/rebels"
               ]
            }
         },
         { 
            "name":"E-11",
			"imgUrl": "img/weapon/assault-weapon/e-11.png",
            "summary":{ 
               "factions":[ 
                  "faction/empire"
               ]
            }
         },
         { 
            "name":"EL-16",
			"imgUrl": "img/weapon/assault-weapon/el-16.png",
            "summary":{ 
               "factions":[ 
                  "faction/resistance"
               ]
            }
         },
         { 
            "name":"F-11D",
			"imgUrl": "img/weapon/assault-weapon/f-11d.png",
            "summary":{ 
               "factions":[ 
                  "faction/first-order"
               ]
            }
         },
         { 
            "name":"A280",
			"imgUrl": "img/weapon/assault-weapon/a280.png",
            "summary":{ 
               "factions":[ 
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         },
         { 
            "name":"CR-2",
			"imgUrl": "img/weapon/assault-weapon/cr-2.png",
            "summary":{ 
               "factions":[ 
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         },
         { 
            "name":"EL-16HFE",
			"imgUrl": "img/weapon/assault-weapon/el-16hfe.png",
            "summary":{ 
               "factions":[ 
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         }
      ],
      "heavy-weapon":[ 
         { 
            "name":"DC-15",
            "summary":{ 
               "factions":[ 
                  "faction/republic"
               ]
            }
         },
         { 
            "name":"E-5C",
            "summary":{ 
               "factions":[ 
                  "faction/separatists"
               ]
            }
         },
         { 
            "name":"RT-97C",
            "summary":{ 
               "factions":[ 
                  "faction/rebels"
               ]
            }
         },
         { 
            "name":"DLT-19",
            "summary":{ 
               "factions":[ 
                  "faction/empire"
               ]
            }
         },
         { 
            "name":"M-45",
            "summary":{ 
               "factions":[ 
                  "faction/resistance"
               ]
            }
         },
         { 
            "name":"FWMB-10",
            "summary":{ 
               "factions":[ 
                  "faction/first-order"
               ]
            }
         },
         { 
            "name":"DC-15LE",
            "summary":{ 
               "factions":[ 
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         },
         { 
            "name":"FWMB10",
            "summary":{ 
               "factions":[ 
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         },
         { 
            "name":"TL-50 Heavy Repeater",
            "summary":{ 
               "factions":[ 
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         }
      ],
      "officer-weapon":[ 
         { 
            "name":"DC-17",
            "summary":{ 
               "factions":[ 
                  "faction/republic"
               ]
            }
         },
         { 
            "name":"RG-4D",
            "summary":{ 
               "factions":[ 
                  "faction/separatists"
               ]
            }
         },
         { 
            "name":"DH-17",
            "summary":{ 
               "factions":[ 
                  "faction/rebels"
               ]
            }
         },
         { 
            "name":"RK-3",
            "summary":{ 
               "factions":[ 
                  "faction/empire"
               ]
            }
         },
         { 
            "name":"GLIE-44",
            "summary":{ 
               "factions":[ 
                  "faction/resistance"
               ]
            }
         },
         { 
            "name":"SE-44",
            "summary":{ 
               "factions":[ 
                  "faction/first-order"
               ]
            }
         },
         { 
            "name":"Blurrg-1120",
            "summary":{ 
               "factions":[ 
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         },
         { 
            "name":"S-5",
            "summary":{ 
               "factions":[ 
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         },
         { 
            "name":"SE-44C",
            "summary":{ 
               "factions":[ 
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         }
      ],
      "specialist-weapon":[ 
         { 
            "name":"Valken-38X",
            "summary":{ 
               "factions":[ 
                  "faction/republic"
               ]
            }
         },
         { 
            "name":"E-5S",
            "summary":{ 
               "factions":[ 
                  "faction/separatists"
               ]
            }
         },
         { 
            "name":"DLT-20A",
            "summary":{ 
               "factions":[ 
                  "faction/rebels"
               ]
            }
         },
         { 
            "name":"DLT-19X",
            "summary":{ 
               "factions":[ 
                  "faction/empire"
               ]
            }
         },
         { 
            "name":"A180-Sniper",
            "summary":{ 
               "factions":[ 
                  "faction/resistance"
               ]
            }
         },
         { 
            "name":"DLT-19D",
            "summary":{ 
               "factions":[ 
                  "faction/first-order"
               ]
            }
         },
         { 
            "name":"A280-CFE",
            "summary":{ 
               "factions":[ 
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         },
         { 
            "name":"IQA-11",
            "summary":{ 
               "factions":[ 
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         },
         { 
            "name":"NT-242",
            "summary":{ 
               "factions":[ 
                  "faction/republic",
                  "faction/separatists",
                  "faction/rebels",
                  "faction/empire",
                  "faction/resistance",
                  "faction/first-order"
               ]
            }
         }
      ],
      "reinforcement-weapon":[ 

      ],
      "starcard-weapon":[ 

      ],
      "hero-weapon":[ 
      ]
   },
   "rumours":{
	   "hero": [ 
      { 
         "name":"Ahsoka Tano",
            "imgUrl":"img/rumour/hero/ahsoka-tano.png",
      },
      { 
         "name":"Padme Amidala",
            "imgUrl":"img/rumour/hero/padme-amidala.jpg",
      },
      { 
         "name":"Asajj Ventress",
            "imgUrl":"img/rumour/hero/asajj-ventress.jpg",
      }
   ]
   }
}